apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: dockersamples/examplevotingapp_vote:before
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS
              value: redis
            - name: REDIS_PORT
              value: "6379"
          readinessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "300m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: voting-app
spec:
  selector:
    app: vote
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
